#!/bin/bash -x
# author : sjn
# date : July.2017

BINDIR=`pwd`
TYPICAL="-typical"
MEGA="-megarow"
EXTENSION=${TYPICAL}

if [ ! -z "$1" ]
then
	ok=`echo "$1" | awk 'toupper($1) == "MEGA"' | awk 'END { print NR }'`
	if [ $ok -eq 0 ]
	then
		printf "Bad argument: must be no arguments or 'mega'\n"
		exit -1
	fi
	EXTENSION=${MEGA}
fi

variablename=$(find ${BINDIR}/ -maxdepth 1 -mindepth 1 -type f -name *${EXTENSION} -print0 | xargs -L1 -0 -I{} sh -c 'basename {}')
for i in ${variablename}; do
	nm=`echo $i | sed "s/${EXTENSION}//"`;
	ln -sf $i ${BINDIR}/${nm};
done

exit 0
