#!/bin/bash
# author : sjn + apr
# date : July.2017

BINDIR=$(dirname $0)

CMD="switch-BEDOPS-binary-type"

help()
{
    echo "Switch the BEDOPS binary build to typical, megarow, or float128"
    echo "Usage: ${CMD} [ --help ] [ --typical | --megarow | --float128 ]" >&2
    exit $1
}

TYPICAL=false
MEGAROW=false
FLOAT128=false
CMD_TYPICAL="make -C ${BINDIR}/../ symlink_typical"
CMD_MEGAROW="make -C ${BINDIR}/../ symlink_megarow"
CMD_FLOAT128="make -C ${BINDIR}/../ symlink_float128"

OPTSPEC=":tmfh-:"
while getopts "$OPTSPEC" OPTCHAR; do
    case "${OPTCHAR}" in
        -)
            case "${OPTARG}" in
                typical)
                    TYPICAL=true
                    ;;
                megarow)
                    MEGAROW=true
                    ;;
                float128)
                    FLOAT128=true
                    ;;
                help)
                    help 0
                    ;;
                *)
                    help 1
                    ;;
            esac;;
        t)
            TYPICAL=true
            ;;
        m)
            MEGAROW=true
            ;;
        f)
            FLOAT128=true
            ;;
        h)
            help 0
            ;;
        *)
            help 1
            ;;
    esac
done

if [[ $# -eq 0 ]]
then
    help 1
fi


cntr=0
if $MEGAROW ; then ((cntr+=1)); CMD=${CMD_MEGAROW}; fi
if $TYPICAL ; then ((cntr+=1)); CMD=${CMD_TYPICAL}; fi
if $FLOAT128 ; then ((cntr+=1)); CMD=${CMD_FLOAT128}; fi

if [[ "$cntr" -ne "1" ]]
then
  help 1
fi

${CMD}

exit 0
