#!/bin/bash
# author : sjn + apr
# date : July.2017

BINDIR=$(dirname $0)

CMD="switch-BEDOPS-binary-type"

help()
{
    echo "Switch the BEDOPS binary build to typical, megarow, or float128"
    echo "Usage: ${CMD} [ --help ] [ --typical | --megarow | --float128 ]" >&2
    exit $1
}

TYPICAL=false
MEGAROW=false
FLOAT128=false
EXTENSION="null"

OPTSPEC=":tmfh-:"
while getopts "$OPTSPEC" OPTCHAR; do
    case "${OPTCHAR}" in
        -)
            case "${OPTARG}" in
                typical)
                    TYPICAL=true
                    EXTENSION="-typical"
                    ;;
                megarow)
                    MEGAROW=true
                    EXTENSION="-megarow"
                    ;;
                float128)
                    FLOAT128=true
                    EXTENSION="-float128"
                    ;;
                help)
                    help 0
                    ;;
                *)
                    help 1
                    ;;
            esac;;
        t)
            TYPICAL=true
            EXTENSION="-typical"
            ;;
        m)
            MEGAROW=true
            EXTENSION="-megarow"
            ;;
        f)
            FLOAT128=true
            EXTENSION="-float128"
            ;;
        h)
            help 0
            ;;
        *)
            help 1
            ;;
    esac
done

if [[ $# -eq 0 ]]
then
    help 1
fi


cntr=0
if $MEGAROW ; then ((cntr+=1)); fi
if $TYPICAL ; then ((cntr+=1)); fi
if $FLOAT128 ; then ((cntr+=1)); fi

if [[ "$cntr" -ne "1" ]]
then
  help 1
fi

WD=$(pwd)
VARNAME=$(find ${BINDIR}/ -maxdepth 1 -mindepth 1 -type f -name \*${EXTENSION})
for V in ${VARNAME} 
do
    BV=$(basename "$V")
    NAME=`echo $BV | sed "s/${EXTENSION}//"`
    cd ${BINDIR}
    ln -sf ${BV} ${NAME}
    cd ${WD}
done

exit 0
